<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Impresiones3D.Domain\Impresiones3D.Domain.csproj" />
    <ProjectReference Include="..\Impresiones3D.Infrastructure\Impresiones3D.Infrastructure.csproj" />
  </ItemGroup>

</Project>
